name: Man10BookMaker
version: 0.1
api-version: 1.17
main: red.man10.BookMakerPlugin
authors:
   - Shupro
   - tororo_1066
softdepend:
   - Man10Kit
depend:
   - WorldGuard
description: Man10 BookMaker Gambling system
commands:
   mb:
      description: Man10 BookMaker Gambling system
      permission: man10.mb
      permission-message: You don't have <permission>
