athletic:
  name: "アスレチック"
  playerNumber: 2
  item: "OAK_PLANKS"
  joinFee: 1000
  tax: 0.0
  prize: 0.05
  virtualBet: 20000
  time1: 30
  time2: 30
  time3: 120

mysql:
  host: localhost
  port: 3306
  user: root
  pass: pass
  db: bookmaker

enable: true

whitelist: